service: image-resizer

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

functions:
  resizeImage:
    handler: index.handler
    events:
      - http:
          path: resize
          method: get